add event_extension var
fivetran/dbt_iterable_source pull request #31
Opened 2024-07-17 22:03 UTC by fivetran-reneeli

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [ ] All necessary documentation and version upgrades have been applied
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [ ] BuildKite integration tests are passing
- [ ] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-07-18 19:58 UTC, fivetran-reneeli commented
will regen docs upon approval

2024-07-22 16:46 UTC, fivetran-avinash commented on CHANGELOG.md
> +- Introduces variable `iterable__using_event_extension` to disable the `stg_iterable__event_extension` model. This allows the downstream models to run even if the source `event_extension` table does
```suggestion
- Introduces variable `iterable__using_event_extension` to disable the `stg_iterable__event_extension` model. This allows the downstream models to run even if the source `event_extension` table does not exist. For more information on how to configure refer to the [README](https://github.com/fivetran/dbt_iterable_source/blob/main/README.md#step-4-enablingdisabling-models).
```

2024-07-22 16:46 UTC, fivetran-avinash commented on README.md
> +This package includes fields we judged were standard across Iterable users. However, the Fivetran connector allows for additional columns to be brought through in the `event_extension` and `user_hist
```suggestion
This package includes fields we judged were standard across Iterable users. However, the Fivetran connector allows for additional columns to be brought through in the `event_extension` and `user_history` objects. Therefore, if you wish to bring them through, leverage our passthrough column variables. For `event_extension` columns, ensure that `iterable__using_event_extension` is set to True, which is the default.
```

2024-07-23 20:56 UTC, fivetran-avinash reviewed
Thanks @fivetran-reneeli !  Let me know when you've regenerated docs and I can go ahead and approve this.

2024-07-24 15:32 UTC, fivetran-avinash approved these changes
@fivetran-reneeli Approved!

2024-07-24 19:55 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for working on this PR. This mostly looks good there is just one final update that needs to be applied:
- You need to add the [config: enabled: block](https://github.com/fivetran/dbt_iterable_source/blob/942a45b10db725a21d2e275f986e0754ed00f341/models/src_iterable.yml#L53-L54) to the [src.yml for the event_extension source table](https://github.com/fivetran/dbt_iterable_source/blob/942a45b10db725a21d2e275f986e0754ed00f341/models/src_iterable.yml#L138-L141). This way, if the event_extension model is disabled then the source freshness will not be run for that source. If we do not include this logic the source freshness test will fail.
![image](https://github.com/user-attachments/assets/49a68b6f-fb50-4a93-b967-a4eb31189c2a)

2024-07-25 19:17 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-reneeli thanks for making these changes. This looks good to me!

2024-07-25 19:54 UTC, merged